name: CI

on: [push, pull_request]

jobs:
  test-and-figures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: make install
      - name: Run tests
        run: make test
      - name: Generate figures
        run: make figs
      - name: Upload figs
        uses: actions/upload-artifact@v4
        with:
          name: figures
          path: figures
